### ISSUE TITLE
Voxelsniper permissions not working with groupmanager - internal server error

### ISSUE THREAD

**Issue by MarkLyck** [TVPT/VoxelSniper#244]
Alright. I've been using voxelsniper just fine with permissionsex for a while. However we've now changed to groupmanager and are experiencing issues.

The plugin works fine for  our opped players.

However players even with the permission:
voxelsniper.*

(which is the one they had before)

cannot do anything. Just says: 

"I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."

Now if I give them access to voxelsniper.sniper

It will let them type in a command.

But it will also kick them of the server with "Internal Server Error"

and create this error in the log: 
http://pastebin.com/MxgGp0iW

Hope you can help us :0

**Comment by Kainzo** [comment]
Edit your wepif.yml file. 
ignore-nijiperms-bridges: true
resolvers:
    enabled:
    - PluginPermissionsResolver
    - PermissionsExResolver
    - bPermissionsResolver
    - GroupManagerResolver
    - NijiPermissionsResolver
    - DinnerPermsResolver
    - FlatFilePermissionsResolver
