### ISSUE TITLE
Not placing Blocks

### ISSUE THREAD

**Issue by TWSSYesterday** [TVPT/VoxelSniper#259]
All commands return valid responses, however placing a specified block doesn't work as it should.
When I use the default settings (doing no commands) the placing of air works as it should do.
Log: http://pastebin.com/uVjsmhQc
Using Spigot version: CraftBukkit version git-Spigot-081dfa5-4470462 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
Plugins (7): AsyncWorldEditInjector, CleanroomGenerator, CoreProtect, WorldEdit, AsyncWorldEdit, VoxelSniper, Multiverse-Core
VoxelSniper Version: (#358) http://ci.voxelmodpack.com/job/VoxelSniper/358/
As said, when I right click when holding an arrow after doing the commands below, nothing happens.
Commands:
- /b ball
- /b 5
- /v stone

**Comment by TWSSYesterday** [comment]
Used latest version of Spigot too, same issue occurs.
Also like to add, when I try to place the ball, no error occurs in the log/console.

**Comment by gabizou** [comment]
Mind you the latest version of VoxelSniper is still in heavy development. We'll investigate this issue and/or resolve the issue. Please use the last VoxelSniper 5.X for Bukkit until VS7 is released for production.

**Comment by Deamon5550** [comment]
You either:

A) sniped into a non-generated chunk, its a known issue.
B) had the misfortune to manage to download a copy with an improper origin offset on undo cache creation that was on jenkins a few days ago.

Both of these issues are already known and will be fixed.

I'd like to reiterate that these current builds are untested and have no support. I'll promote a build for as a beta as soon as enough legacy features are replicated and the system is stable, but until then I'll not be taking issue reports.

**Comment by TWSSYesterday** [comment]
I used the latest Jenkins version, and the chunk was generated. Any ideas? Configuration files are default.

**Comment by Deamon5550** [comment]
Try jenkins [#359](http://ci.voxelmodpack.com/view/VoxelSniper/job/VoxelSniper/359/)

**Comment by TWSSYesterday** [comment]
Still no, when I go to place, I see this:
13:11:42 [INFO] [VoxelSniper] Snipe at CommonLocation (Builds: 71.0, 36.0, 57.0)
13:11:43 [INFO] [VoxelSniper] Snipe at CommonLocation (Builds: 60.0, 36.0, 47.0)
13:11:44 [INFO] [VoxelSniper] Snipe at CommonLocation (Builds: 60.0, 36.0, 47.0)

**Comment by TWSSYesterday** [comment]
Update on this @Deamon5550 ? :)

**Comment by Deamon5550** [comment]
As I stated earlier I don't wish to provide support for unstable and untested builds. As soon as the system is more stable I'll promote a build as beta and only then will I look at issues that are occurring.

**Comment by Deamon5550** [comment]
In saying that I just reread your first post, the command your looking for to select your brush is `/b ball material` not `/b ball`

**Comment by TWSSYesterday** [comment]
Works, thanks.

**Comment by TWSSYesterday** [comment]
http://pastebin.com/D7bXFyUE
Spigot: 2130aaa-c8f1723
VoxelSniper http://ci.voxelmodpack.com/job/VoxelSniper/361/
Exactly same issue.

**Comment by Deamon5550** [comment]
>As I stated earlier I don't wish to provide support for unstable and untested builds. As soon as the system is more stable I'll promote a build as beta and only then will I look at issues that are occurring.
