### ISSUE TITLE
Issue with LWC and other plugins Combo causeing LWC to not load

### ISSUE THREAD

**Issue by Echen-kraul** [TVPT/VoxelSniper#260]
I ran into a problem with LWC in which it wouldnt load properly on startup. at first it would seem this is a problem with LWC but further testing revealed that LWC loads properly with Voxelsniper by themselves and LWC loads properly with numerous plugins as it should. however when voxelsniper and LWC are them combined with other plugins it causes LWC to not load. Multiverse, MCTowns, and many others will cause LWC to break (again this info seems to point that something is wrong with LWC) however i can load over 50 plugins, including the above mentioned and many more that cause the issue with LWC and they all load properly until i add VoxelSniper.

The following was a post i made on the LWC spigot Forum found at http://www.spigotmc.org/threads/lwc.37440/page-3

Ok... in doing some testing I found that it was, (so i thought) VoxelSniper that is causeing the issue. however testing further seems to show that LWC and voxel sniper work fine together when alone.

Startup with just LWC http://pastebin.com/fmJiLMJR

Startup with LWC and Voxelsniper (Edit: apparently i lost this log but there were no errors to report)

however with all my plugins i get this startup http://pastebin.com/MT6Hq0Th

But if i remove voxelsniper.... LWC starts working again.... http://pastebin.com/h8gH5Z9t

Update: I did some further testing, starting with just voxelsniper and LWC and added in plugins one at a time. i found that a number of plugins cause LWC to not load, to include OpenInv, Mob_Cash, MCTowns, MultiVerse and it wouldnt surprise me if there were more but i stopped there because it was just confusing as to how some of these plugins were even effecting how VoxelSniper OR LWC function. regardless ALL of them load properly by simply removing VoxelSniper which really makes no sense to me but as proof..... 

All plugins WITH voxelsniper http://pastebin.com/QaSnp6t1

All plugins WITHOUT voxelsniper http://pastebin.com/30wF1GcN

and again i point to the above pastebins to see that by themselves both LWC and VoxelSniper DO load fine together when alone. but add in Multiverse or MCtowns or a host of other plugins and it breaks.

As I have come to the conclusion that this is most likely an issue on VoxelSnipers part ill be sending this info to them as well but just wanted everyone to be aware of my findings in case someone has a similar issue.

I would like to add that this issue seems to only be VoxelSniper 7.0.0

VoxelSniper 5.170.0 does not cause this issue.

**Comment by Deamon5550** [comment]
I think I've an idea of what this might be. Give this jar file a try: http://files.thevoxelbox.com/VoxelSniper-Bukkit-7.0.0-SNAPSHOT-all.jar and let me know how it works out with all your plugins.

**Comment by Echen-kraul** [comment]
just checked my email and got this message. i tossed it on the server and started it up and everything loaded properly. Im about to go to bed cause i gotta work early in the morning but ill test it out some as soon as i can.
http://pastebin.com/zJxgxfry
 



     On Saturday, March 21, 2015 1:01 PM, Nick Conde <notifications@github.com> wrote:
   

 I think I've an idea of what this might be. Give this jar file a try: http://files.thevoxelbox.com/VoxelSniper-Bukkit-7.0.0-SNAPSHOT-all.jar and let me know how it works out with all your plugins.—

**Comment by Deamon5550** [comment]
Should be fixed on master as of 782ef640805efd99cf9 [Build](http://ci.voxelmodpack.com/view/VoxelSniper/job/VoxelSniper/375/).
