### ISSUE TITLE
Plugin wont load 

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [TVPT/VoxelSniper#262]
http://pastebin.com/b1kG7GY0

**Comment by Deamon5550** [comment]
You are using the wrong jar from the ci. You need [VoxelSniper-7.0.0-SNAPSHOT-all.jar](http://ci.voxelmodpack.com/view/VoxelSniper/job/VoxelSniper/lastSuccessfulBuild/artifact/build/libs/VoxelSniper-7.0.0-SNAPSHOT-all.jar).

Please do note that you are using a very early and untested version of the next release of sniper. If you are wanting a fully functional copy of sniper you are looking for [VoxelSniper-5.170.0.jar](http://files.thevoxelbox.com/Plugins/VoxelSniper/VoxelSniper-5.170.0.jar).

**Comment by TheOnlyRealTGS** [comment]
Okay
