### ISSUE TITLE
All players are seeing the login message, despite no perms.

### ISSUE THREAD

**Issue by PsychoNavigator** [TVPT/VoxelSniper#263]
Currently using the latest version plugin that was released two months ago.

On player login they are seeing the login message created by VS. The only group that has VS perms are Admin. Players in all ranks see it, but cant do anything with it. There's no wildcards in use that would allow this.

Any ideas?

**Comment by Deamon5550** [comment]
What version are you using? There haven't been any releases but if you say that you are using a version from two months ago its likely that you are using version 7 which is not yet stable. I highly advise that until version 7 is stable that you keep using [version 5](http://dev.bukkit.org/media/files/796/868/VoxelSniper-5.170.0-SNAPSHOT.jar).

**Comment by PsychoNavigator** [comment]
Yes, version 7. I'll revert but it's not mission critical.

Figured it was worth bringing to light, is all.

**Comment by Deamon5550** [comment]
Yeah I'll leave this issue here so that I don't forget it, thanks.

**Comment by Deamon5550** [comment]
shouldn't exist anymore in the [latest release for sponge 1.10.2](http://ci.voxelmodpack.com/view/VoxelSniper/job/VoxelSniper/)
