### ISSUE TITLE
Verbosity configuration node

### ISSUE THREAD

**Issue by varrix** [TVPT/VoxelSniper#268]
It would be super appreciated if we could configure the logger level. This is primarily stemmed from the amount of messages logged during the server startup (not exact event). It would be great to not *always* see them. This will extend to other messages in the future of course as I'm sure more information will be logged down the line.

**Comment by Deamon5550** [comment]
For sure, a lot of those messages can probably just go away as well.

**Comment by Deamon5550** [comment]
No longer an issue in the [latest release for sponge 1.10.2](http://ci.voxelmodpack.com/view/VoxelSniper/job/VoxelSniper/)
