### ISSUE TITLE
Does build #408 not work on Spigot 1.8.8?

### ISSUE THREAD

**Issue by FrozenBeard** [TVPT/VoxelSniper#271]
I cant get the VoxelSniper build 408 to load on Spigot 1.8.8 at bootup, does it have dependancies? or does it just not work with the latest spigot yet?

**Comment by gabizou** [comment]
Did you use the -all build?

**Comment by FrozenBeard** [comment]
@gabizou I did not! I will give this a bash! *gets excited* 
Im not even joking when I say Voxelsniper is my all time favorite plugin I miss from my server since updating from 1.7.9 all that time ago, im very exited that its been in active development recently.
