### ISSUE TITLE
Voxel Sniper

### ISSUE THREAD

**Issue by v1ghost** [TVPT/VoxelSniper#272]
when ever i do /b e melt or /b e fill it says "could not find a brush part named E" can any one help?
![2015-09-28_12 37 36](https://cloud.githubusercontent.com/assets/14136142/10126948/e5d59552-65dd-11e5-9161-8cac6eab52cf.png)

**Comment by Deamon5550** [comment]
Brushes have changed and the melt brush has not been moved into the new version yet see [the documentation](https://github.com/TVPT/VoxelGunsmith/wiki/Quick-Reference#brushes) for a list of brushes and parameters (also look at the new command syntax).
