### ISSUE TITLE
Overlay and smooth

### ISSUE THREAD

**Issue by kungfalco** [TVPT/VoxelSniper#273]
How do I use the old overlay and smooth brush!

I can't use them any more.

**Comment by Crayder** [comment]
Same here, they seem to be removed.

**Comment by Crayder** [comment]
It seems to me like the last time they even existed were in this commit:
https://github.com/TVPT/VoxelSniper/tree/1a17ed8cbd261714700af16f909ece823cbe066e/src/main/java/com/thevoxelbox/voxelsniper

**Comment by gabizou** [comment]
> The commit after that one, by @gabizou, removed it. I would really like to know why...

Because VoxelSniper has since been rewritten from scratch... @Deamon5550 may or may not have added the overlay/smooth brushes since the rewrite, but those specific brushes would be registered in [VoxelGunsmith](https://github.com/TVPT/VoxelGunsmith).

**Comment by Crayder** [comment]
Thanks for the info, and I hope @Deamon5550 see's this soon, for an answer at the least.

**Comment by Deamon5550** [comment]
No longer an issue in the [latest release for sponge 1.10.2](http://ci.voxelmodpack.com/view/VoxelSniper/job/VoxelSniper/)
