### ISSUE TITLE
How usable is the current build?

### ISSUE THREAD

**Issue by SupaCURE** [TVPT/VoxelSniper#274]
Hey, just been testing out the new dev build on my server, used to use this plugin all the time back in the day. Using build #409.

Seems to lack certain commands like /b e melt, and not sure if I'm using the material performers properly but No Physics isn't working as far as I can tell (I may be using the command wrong honestly, it's been a while).

Apologies if these issues are already known I'm just not familiar with where you guys are in the remake.

Was testing with the snipe tool earlier but the only issue I had like I mentioned was that the no physics performer was seemingly broken.

**Comment by DrSulfurious** [comment]
Guess I should mention with some playing around I was able to figure out how to use a blend brush. Apologies, that seems close enough to the melt tool for the time being. (/b ball blend)

Still not sure how to apply the no physics performer though.

**Comment by Deamon5550** [comment]
The current builds are fairly usable, I'm afraid I've not been able to dedicate the time recently to push it that final bit into being stable.

The erosion brushes are not currently in although there is blend like you found.

Performers are a thing of the past but I have not added back in the no-phys options yet, but it'll be a global setting similar to how `/vs range` used to work.

For the most recent docs see https://github.com/TVPT/VoxelGunsmith/wiki/Quick-Reference

**Comment by DrSulfurious** [comment]
Thanks a ton. You guys got an IRC channel or something? Wouldn't mind hanging around if you're up for a bit of discussion every now and then.

**Comment by Deamon5550** [comment]
theres #voxelbox on irc.esper.net, not much discussion if you ask something I'll usually respond.
