### ISSUE TITLE
VoxelSniper will not load with 1.7.10's Forge v10.13.4.1517

### ISSUE THREAD

**Issue by TomeWyrm** [TVPT/VoxelSniper#275]
If this is intended, you should probably note that you do not support 1.7.10 (As it is still by far the most common/active modded version of Minecraft) on this page: https://github.com/TVPT/VoxelGunsmith/wiki

If this is not intended here is my log: https://paste.ee/p/6GIyR
I'm using VoxelSniper-7.1.0-SNAPSHOT-all.jar - BUILD #413

**Comment by Deamon5550** [comment]
We don't support 1.7.10
