### ISSUE TITLE
VS7 completely broken on latest 1.8.8

### ISSUE THREAD

**Issue by CKGAR** [TVPT/VoxelSniper#279]
The most recent Dev builds on Jenkins do not work at all on 1.8.8. I have tried all 3 .jar files and my server doesn't even try to load them, there aren't any error messages or indicators it is even trying to start. Running the latest Spigot 1.8.8.

**Comment by Deamon5550** [comment]
Use version 5 on spigot, version 7 is still in development and not supported at all.

**Comment by CKGAR** [comment]
If VS7 isn't supported on 1.8 versions, you mught want to stop telling people it is on BukkitDev.

**Comment by Deamon5550** [comment]
7.1.0 is in development and not feature complete, most likely you're simply running the wrong jar file but if you're using spigot you may as well just use version 5 right now.

The correct jar for referemnce http://ci.voxelmodpack.com/view/VoxelSniper/job/VoxelSniper/lastSuccessfulBuild/artifact/build/libs/VoxelSniper-7.1.0-SNAPSHOT-all.jar
