### ISSUE TITLE
How to disable the join message for VoxelSniper?

### ISSUE THREAD

**Issue by flyinggoatman** [TVPT/VoxelSniper#285]
I had a look around for a while but could only find this post by **@JackzTaEpic**.
- https://github.com/TVPT/VoxelSniper/issues/213

The staff memeber ( **@MikeMatrix** ) says it can now be done. Can someone please let me know how this can be done? thanks :+1:

**Comment by TheCodingHoodie** [comment]
@flyinggoatman the way you disable the join message are as follows:
1. Go to the server folder
2. Go to plugins > VoxelSniper
3. In the folder, open config.yml in your text editor.
4. Change "message-on-login-enabled" to false, and save the file.
5. Restart/reload your server and test it out!

**Comment by Deamon5550** [comment]
@TheCodingHoodie That will work for version 5.170 but anything version 7+ will require me adding a new configuration option for it, just haven't gotten the time to do it yet.
