### ISSUE TITLE
Voxelsniper 5.170.0 and up - Permission Issue an work around (/b b m)

### ISSUE THREAD

**Issue by SilberRegen** [TVPT/VoxelSniper#290]
I figured this one out purely by chance.
I had issues with using any version after VoxelSniper 5.168.9-SNAPSHOT since they would spill out internal errors with the command /b b m and similar.
This happens only, if the person using voxelsniper doesn't have the permission voxelsniper.\* , but voxelsniper.sniper instead, which doesn't seem to work properly anymore.

Error: User Tolkier has voxelsniper.\* (which he needed for a Voxelsniper 7 testrun), MetalGandalf does not.
http://pastebin.com/WQPcsu3W

**Comment by Deamon5550** [comment]
Versions targetting bukkit are no longer suppported. (also that kind of permission issue is the fault of spigot not voxelsniper)
