### ISSUE TITLE
Help me ! please ;-;

### ISSUE THREAD

**Issue by Lyrtix** [TVPT/VoxelSniper#291]
Hello i get the following error in my console when doing some command (exemple: /b v 2) http://pastebin.com/3nJ60DGL

I also got no brush selected when i click (right or left) with the arrow or the gunpowder

But when i do a right click on a block with nothing in hand that makes me a Spher of 5 radius

Thanks for reading ! 

Ps : i have World Edit

And sorry for my bad english i'm french ^^'

**Comment by Deamon5550** [comment]
Versions targetting bukkit are no longer supported.
