### ISSUE TITLE
Voxelsniper for 1.10 Sponge

### ISSUE THREAD

**Issue by P42C41** [TVPT/VoxelSniper#292]
Hello,

just want to ask when you'll update the Mod to the latest Sponge API.

I always get a error when i rightclick with a Voxel Item: http://hastebin.com/avogedukay.avrasm

Best regards, Pascal

**Comment by Deamon5550** [comment]
[latest release for sponge 1.10.2](http://ci.voxelmodpack.com/view/VoxelSniper/job/VoxelSniper/)
