### ISSUE TITLE
issue with selecting specific multi type block

### ISSUE THREAD

**Issue by Icefang23** [TVPT/VoxelSniper#293]
Whenever I try to select a color or type specific bock that is not the default type it either selects the default one or if I use the command, it will say the block is not valid. for example I want  to select red hardened clay for the voxel tool but when I try /v 159:14, the plugin does not recognize it as a valid bock ID. however the plugin dose recognize the "default" white hardened clay (159).  This plugin did not have this issue until I updated the server from 1.8 to 1.9.4 even though I updated the plugin. Am I doing something incorrect or does the plugin need to be updated?

**Comment by Deamon5550** [comment]
What version and what platform?

**Comment by Icefang23** [comment]
My server is a paper spigot server version 1.9.4 I'm using voxelsniper 5.171.0 snapshot

**Comment by Deamon5550** [comment]
oh I'm a derp, you don't select the data value in that way, you'd use `/v 159` to select the block id and then `/vi 14` to set the data value.

**Comment by Icefang23** [comment]
ok thanks ill try that

**Comment by Icefang23** [comment]
now one more question, when preforming the command /b b cc how do I select the replacement material? I thought you would do it with one if the tools but its just replacing the air with the material.
