### ISSUE TITLE
VS 5.170.0-SNAPSHOT Metrics error with MC 1.10

### ISSUE THREAD

**Issue by elFlashor** [TVPT/VoxelSniper#294]
I get recurring error in the log due to an unknown method in Metrics bundled in VoxelSniper:

05.10 09:21:03 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
05.10 09:21:03 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
05.10 09:21:03 [Server] INFO at org.mcstats.Metrics$1.run(Metrics.java:223)
05.10 09:21:03 [Server] INFO at org.mcstats.Metrics.access$400(Metrics.java:57)
05.10 09:21:03 [Server] INFO at org.mcstats.Metrics.postPlugin(Metrics.java:335)
05.10 09:21:03 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
05.10 09:21:03 [Server] INFO at java.lang.Thread.run(Thread.java:745)
05.10 09:21:03 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
05.10 09:21:03 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
05.10 09:21:03 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
05.10 09:21:03 [Server] INFO [09:21:03 WARN]: org.apache.commons.lang.UnhandledException: Plugin VoxelSniper v5.170.0-SNAPSHOT-jnks317-gitfcb8fe1 generated an exception while executing task 25
05.10 09:21:03 [Server] INFO [09:21:03 WARN]: Exception in thread "Craft Scheduler Thread - 7018"

This error pop ups every 15 minutes in the console.

**Comment by Deamon5550** [comment]
Use [version 5.171.0](https://dev.bukkit.org/bukkit-plugins/voxelsniper/files/23-voxel-sniper-5-171-0-mc-1-9/)
