### ISSUE TITLE
Voxelsniper tools do not work outside of interact range

### ISSUE THREAD

**Issue by Khitiara** [TVPT/VoxelSniper#295]
VS 8.0.0 (last successful jenkins)
SpongeForge BETA-1808
Forge 12.18.2.2107
Minecraft 1.10.2

Brushes do nothing unless the target block's bounding box is visible

**Comment by Deamon5550** [comment]
This is likely due to some recent changes to sponge's interact events, I'll need to add a new event listener probably.

**Comment by jcomack** [comment]
+1

Running into the same issue with the same configuration.

**Comment by ayyy** [comment]
Any ETA on the fix for this? @Deamon5550
