### ISSUE TITLE
SpalatterBall IndexOutOfBounds

### ISSUE THREAD

**Issue by vectrixdevelops** [TVPT/VoxelSniper#296]
https://gist.github.com/connorhartley/4f0f892cb76bf52be4bb30d604b5115c

**Comment by JacobCZ** [comment]
I have the exact same problem...

**Sponge Vanilla**
Minecraft: 1.10.2
SpongeAPI: 5.1.0-SNAPSHOT-682caf3
SpongeVanilla: 1.10.2-5.1.0-BETA-365

**Comment by vectrixdevelops** [comment]
@Deamon5550 any ideas?
