### ISSUE TITLE
Tree Types

### ISSUE THREAD

**Issue by Kaelico** [TVPT/VoxelSniper#300]
When attempting to change the tree type it says "Tree type not found" even after confirm with /b tree types

**Comment by Deamon5550** [comment]
What version?

**Comment by Kaelico** [comment]
Sorry, about not including the version number. Forgot about that completely ha ha.
Minecraft 1.10.2
Forge 12.18.3.2215
Sponge 5.1.0 Beta 2039
VoxelSniper 8.2.0 Build #447
