### ISSUE TITLE
Large Trees

### ISSUE THREAD

**Issue by Kaelico** [TVPT/VoxelSniper#301]
Minecraft 1.10.2
Forge 12.18.3.2215
Sponge 5.1.0 Beta 2039
VoxelSniper 8.2.0 Build #449

When using the tree command it now allows you to change tree types, but changing to large trees reverts to the normal size. 

Picture: When using any tree command it shows that exactly with the type changed depending on the tree chosen.
![screenshot_72](https://cloud.githubusercontent.com/assets/24547924/22052548/cab63840-dcff-11e6-8654-e13d3cbdf27c.png)

**Comment by Deamon5550** [comment]
its just a display error they should work correctly right?

**Comment by Kaelico** [comment]
You're right, it's only a display error. Tested all the trees and noticed the difference in the oak sizes after that. However, using /u with trees doesn't do anything. It returns with the message "There's nothing to undo." I can create a new issue for this if you want.

**Comment by Deamon5550** [comment]
Yeah the undo is a separate issue and one that I may have to make some changes in sponge to support.
