### ISSUE TITLE
Splatter Ball Error

### ISSUE THREAD

**Issue by Kaelico** [TVPT/VoxelSniper#304]
When attempting to use following brush
/b sb mm
/v 0
/b 5

http://pastebin.com/DZemLhHB
Edit Reason: Insert Code didn't seem to work. Replaced with pastebin

Minecraft 1.10.2
Forge 12.18.3.2215
Sponge 5.1.0 Beta 2039
VoxelSniper 8.2.0 Build #449

**Comment by marshmellion** [comment]
this is indeed the most annoying problem i have atm. it happens with any brush using the s performer

ei: soverlay, sb, sd, ect

**Comment by Deamon5550** [comment]
Was fixed in e8d90f80ba4efdd43685ef1cf4b5904000658683
