### ISSUE TITLE
Wool data value

### ISSUE THREAD

**Issue by Kaelico** [TVPT/VoxelSniper#305]
Uses /v wool[color=pink] returns "Voxel: minecraft:wool[color=pink] correctly. However, the wool after using the brush stays white.

EDIT: Same problem happens with logs.

Minecraft 1.10.2
Forge 12.18.3.2215
Sponge 5.1.0 Beta 2059
VoxelSniper 8.2.0 Build #449

**Comment by Deamon5550** [comment]
Make sure you're using a compo performer, although I might think about removing that in the future for now it is still required. (just tested and placing pink wool works fine if you are using a combo performer)
