### ISSUE TITLE
/b over brush, gunpowder works similar to the arrow

### ISSUE THREAD

**Issue by ziment** [TVPT/VoxelSniper#306]
I have some problems with /b over brush
Everyone says that when you use this with gunpowder it supposed to create a new layer of blocks, however, for me it works similar to the arrow (replacing blocks)
Does anyone know how to make gunpowder work like I want to?

**Comment by marshmellion** [comment]
Currently it is either a bug or an unupdated feature. 
Gunpowder will work with /b erode ? Brushes but it will act like an arrow on thing like /bb or overlay. 

To put it short blending and overlay are broken for gunpowder as well as other performers i think.
