### ISSUE TITLE
The Stencil List Brush 

### ISSUE THREAD

**Issue by JonasKruckenberg** [TVPT/VoxelSniper#308]
Hey there !
I wonder whats about the /b sl brush ! when i try to use it it throws an error like this :
java.lang.ArrayIndexOutOfBoundsException: 1  
I've looked into your source code and it seems that it isn't spongified yet ,because you have commented out all main methods. And the paths aren't right yet.
Is there a reason or is it just not finished ?

**Comment by Deamon5550** [comment]
Needs some support from sponge, namely being able to rotate the schematics there and I haven't gotten around to adding that yet.

**Comment by JonasKruckenberg** [comment]
okay thanks ;)
