### ISSUE TITLE
/v command should be changed ASAP

### ISSUE THREAD

**Issue by xtomyserrax** [TVPT/VoxelSniper#324]
Please change the /v command. There are many vanish plugins that use the /v to work. I know you use it as an alias, but /v has been established for vanish in almost all servers.

Thanks!

**Comment by gabizou** [comment]
You can configure that in your server configuration files to direct which plugin gets control of `/v`.

**Comment by ryantheleach** [comment]
To be explicit (if on Sponge): https://docs.spongepowered.org/stable/en/server/getting-started/configuration/sponge-conf.html?highlight=aliases

```
Alias will resolve conflicts when multiple plugins request a specific command. Correct syntax is<unqualified command>=<plugin name> Example:

aliases = {
     v=voxelsniper 
}

```

Will give you back v for voxelsniper as opposed to vanish

Duplicate of : https://github.com/TVPT/VoxelSniper/issues/322

**Comment by xtomyserrax** [comment]
But this has no sense. Every server, every dev, uses /v for vanish purposes, why cant you change your /v command and use /vs or another thing? Again, you are doing the things wrong.

Do you want to use /login too? Or use /r which is used for replies? Or maybe you can use /fly because I think it would be really useful for you...

**Comment by gabizou** [comment]
VoxelSniper predates quite a few plugins, and while sure `/v` could ideally be for a vanish plugin toggle, that's still configurable through your server configs.
