### ISSUE TITLE
/v command should be changed ASAP

### ISSUE THREAD

**Issue by xtomyserrax** [TVPT/VoxelSniper#325]
This topic wasnt fixed: https://github.com/TVPT/VoxelSniper/issues/324#issuecomment-371232184

It is very rude from you not fixing your command. It isnt hard to change it to /vs or /voxel or /vx or something with more sense...

/v = /vanish = COMMON SENSE

**Comment by gabizou** [comment]
You're a server administrator, right? Configure your server how you want it to run. It's not a problem of the plugin at all.
