### ISSUE TITLE
NoClassDefFoundError on Java 9 and above

### ISSUE THREAD

**Issue by J0B10** [TVPT/VoxelSniper#326]
I tried loading the plugin on a server with java 9 and a exception with the folllowing message was thrown:
```
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
```
After doing some research I found out that the JAXB APIs are considered to be Java EE APIs, and therefore are no longer contained on the default class path in Java SE 9.
I could fix this by adding the argument `--add-modules java.se.ee`to the .start.sh of my server.

But as far as I heard this will also be removed in future java versions, so this should be definitly fixed by the plugin.

Where I got my information from:
https://stackoverflow.com/a/43574427

**Comment by gabizou** [comment]
Why are you even using Java 9? Minecraft doesn't even support it.

**Comment by J0B10** [comment]
Just for testing how well it works, always like to keep experimenting a bit. :relaxed:

The spigot server himself is running completly fine so no problems from this side.

Also I want to mention that this is really not a big deal for me if it doesn't work, I just want to let you know about it so you can keep your plugin future proof.
Just like with all other java versions we wont be able to run everything on java 8 forever.

**Comment by gabizou** [comment]
Closing this as the Minecraft tool chain still doesn't support Java 9. Not something VoxelSniper can fix easily.
