### ISSUE TITLE
Spigot 1.13 update?

### ISSUE THREAD

**Issue by andris155** [TVPT/VoxelSniper#328]
Please update this plugin 1.13.

**Comment by gabizou** [comment]
Yeah.... there's enough that's broken in the "bukkit" api that a majority of VoxelSniper would need to be updated for. If someone wishes to take a jab at trying to update the legacy codebase, I've pushed a temporary branch with the dependencies. I'm not keen on rewiring the guts and updating all the brushes and math involved as plenty of the masks are now complicated to replicate as the old system used to without some additions to the Bukkit API to achieve similar functionalities (like "resetting blocks", or cycling between possible states).

It's very well possible to improve the brushes at the same time or introduce changed logic with some explanation of how previous cycling worked and how new cycling could work if block state properties were exposed and there was a simple way to retrieve available properties and apply some sort of permutation operation from string input of the player.

All of this is purely hypothetical though, I don't have the time to invest in improving features or even implementing a system to perform the above. I'm allowing anyone to propose a *working, clean, and tested* PR to upgrade VoxelSniper.

**Comment by BenjaminHoegh** [comment]
FAWE have a updated version of VoxelSniper but sadly it's really buggy in the lasted version.

But I would be willing to pay for this plugin if it means the developers behind will work on it again

**Comment by enterih** [comment]
Yeah i'm also ready buy this plugin. It's an amazing job behind
