### ISSUE TITLE
Voxel Sniper commands don't show up

### ISSUE THREAD

**Issue by DeaSTL** [TVPT/VoxelSniper#329]
I'm on SpongeAPI version 1.1.0-SNAPSHOT-7105dfc
Forge 1.12.2 2757
and the plugins include
SpongeForge
VoxelSniper
WorldEdit
and I am opped on the server but the commands do not seem to be working.

**Comment by gabizou** [comment]
logs?

**Comment by DeaSTL** [comment]
I had the wrong voxel sniper version.
