### ISSUE TITLE
sniper alias overlapping with plotsquared

### ISSUE THREAD

**Issue by prettyinaccurate** [TVPT/VoxelSniper#330]
I'm using VoxelSniper in a creative server that i'm creating and i'm trying to use plotsquared, but the sniper alias [/p] automatically overlaps with the plot alias [/p] and voxel dominates it. Is there some way I can remove the alias, or delete the sniper brush, fix it in any way? cause it won't be very good for hosting a creative server if the /p alias doesn't even work.

**Comment by gabizou** [comment]
Every modern server modification of minecraft has command alias management. You configure it through your server configuration. See the related documentation to the server mod you use (spigot/sponge).
