### ISSUE TITLE
Unable to get the Files

### ISSUE THREAD

**Issue by StreakDragon** [TVPT/VoxelSniper#336]
Can anyone help me, I've been trying to get VoxelSniper on my Sponge Server for a while now, everywhere I go I keep getting bad gateways and with the Jenkins link I signed up and it tells me I don't have overall read permissions...every turn I take I get thwarted and can not get 8.5.0 (build 478?) I have sponge version 7.1.6 RC3616. Can SOMEONE help me here.

Thank you in advance for anyone that can either provide me the file or point me to a working site. I also tried the VoxelSniper IRC Channel (why aren't they using Discord???) and literally no one has answered, spoke or anything else for over 3 days so I'm absolutely stuck.

This is the link I've been trying to follow:  http://ci.voxelmodpack.com/job/VoxelSniper/478/

And if I try to get v8.5.0 from https://forums.spongepowered.org/t/voxelsniper-long-range-terrain-editing-v8-0-0-1-8-9-1-10-2/10695  I get a bad gateway...

**Comment by gabizou** [comment]
Fixed the jenkins. Can now view builds.
