### ISSUE TITLE
i can't access the jenkins server

### ISSUE THREAD

**Issue by WarriorGamingserv** [TVPT/VoxelSniper#340]
Hi, for some reason i can't access the jenkins, and i really want the 1.12 voxelsniper for sponge could someone send it to me or fix the jenkins?

**Comment by Fently** [comment]
Yeah. I had to compile from the source myself. Here it is until they get the Gitlab running again

> *Link removed by moderator*

Edit: Yeah it's safe to say that won't be happening anytime soon. Last time devs even touched this was two years ago. Until someone picks this up, the project is dead
