### ISSUE TITLE
VoxeBox's Maps

### ISSUE THREAD

**Issue by EduMenges** [TVPT/VoxelSniper#352]
This is not a VoxelSniper related issue. I'm posting it here because I found no other way to contact.

So the files.voxelbox.com server has been offline for some time now. Are there any plans to bring it back or to release the worlds? VoxelBox is gone for a long time now, so I don't blame if you decided to delete it.

**Comment by GavJenks** [comment]
I am also interested in this

**Comment by Deamon5550** [comment]
I definitely still have that data somewhere, let me look around a bit and then maybe I can put it on google drive or something.

**Comment by EduMenges** [comment]
> 
> 
> I definitely still have that data somewhere, let me look around a bit and then maybe I can put it on google drive or something.

Did you found it?

**Comment by Deamon5550** [comment]
http://files.thevoxelbox.com/

This should be working again.

**Comment by EduMenges** [comment]
> 
> 
> http://files.thevoxelbox.com/
> 
> This should be working again.

Thanks!
