### ISSUE TITLE
Biomes won't change until I refresh the chunks 

### ISSUE THREAD

**Issue by Naeso** [TVPT/VoxelSniper#356]
Hi,

Noticed this issue in VoxelSniper 1.12 for Sponge API7. I've tried a server with only this plugin installed and no mod on the client to be 100% sure this is not a graphical issue from my side.

What I do it type /b biome Plains, but when clicking with whatever item (gunpowder or arrow) it does nothing visually. I have to reload the chunks by disconnecting or going very far, get back, and see the changes. This is extremely tedious to do.

Thanks.

**Comment by Naeso** [comment]
New information : with further testing, this work only from Sponge 7.1.6, after that version and using further ones, like 7.1.7, or 7.1.8, etc... the feature brokes.

**Comment by gabizou** [comment]
This would be an issue to present to [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/issues) since it is the implementation that implements the API that we're using to change biomes.
