### ISSUE TITLE
Fabric version?

### ISSUE THREAD

**Issue by NeusFear** [TVPT/VoxelSniper#358]
I want to preface this request with a statement from one modder to another. Making mods takes time and maintaining multiple versions isn't great, but I was wondering if there was ever talk or plans to make a Fabric compatible version of this as a serverside mod?

I have used the Sponge version in the past, but don't know how many mixins are used. Fabric has good mixin support, and their API is built on mixins so it's probably possible to start from that branch.

Anyways, thanks for what you do and any response would be welcome.

**Comment by gabizou** [comment]
VoxelSniper has been built on API's only, never using internals or Mixins. The premise to writing a Fabric version would be equivalent to writing a Forge mod version of VS that uses 100% internal code and is therefore obfuscated/reobf'ed for the target platform.

At this time, I barely have enough resources to dedicate to the maintenance of VS to support the two platforms (Sponge and Bukkit), so it'd be a suggestion for anyone who does wish to make a port of the version, under TVPT, would be signing on to maintaining that platform version. 

If it comes down to a multi-platform API being created for VS to work between the platforms, that *might* be doable, but as it stands currently, it's a monstrosity of work to perform, and as such I'm not going to entertain that effort at present.
